### ISSUE TITLE
Not getting this years submissions

### ISSUE THREAD

**Issue by anicolson** [Stanford-AIMI/RRG24#10]
Thanks again for organising RRG24.
 
I am having issues with viewing my submissions for this year.
 
If I put in team name ‘e-Health CSIRO’, I get the submissions from last year’s challenge (and not the ones for this year).

**Comment by jbdel** [comment]
hello,
This shouldnt be happening, do you have an actual example of what happens ?

**Comment by anicolson** [comment]
When I ask for my submissions, I get the ones from last year:
![image](https://github.com/Stanford-AIMI/RRG24/assets/26111230/e3f00b15-68e2-44d3-91a7-a3cce449b864)
![image](https://github.com/Stanford-AIMI/RRG24/assets/26111230/cc58111b-dbd4-4732-a0c4-bc92b57d41b4)

The submissions from this year are not included, e.g., the following submission is not included above:
![image](https://github.com/Stanford-AIMI/RRG24/assets/26111230/8b2761d6-ee5e-40e3-b0a8-018f1c4a0980)

**Comment by jbdel** [comment]
I found the issue. Will fix soon.

Thanks for reporting this

**Comment by jbdel** [comment]
fixed
