### ISSUE TITLE
Submissions to the leaderboard not working

### ISSUE THREAD

**Issue by oscarloch** [Stanford-AIMI/RRG24#12]
I was trying to upload a submission and I got this error:
![Screenshot_9](https://github.com/Stanford-AIMI/RRG24/assets/69605823/88714f33-f6c5-4dea-8bd4-b7c32d990df4)

The file had the same format as previous submissions so I doubt it is a local error.

Thank you so much again for your help!

**Comment by jbdel** [comment]
is it still happening ?

**Comment by oscarloch** [comment]
I just tried and it is still happening

**Comment by jbdel** [comment]
I just tried a submission (ground truth file) and all is good on my side. 
Are you behind a VPN of some kind. No code has been changes since your last submissions.
Which leaderboard is it ?

**Comment by oscarloch** [comment]
I'm not using a VPN; I also tried with different networks.
It is for the findings-public-test-set.

Do you know what events in the code of the webpage may trigger the "Notification: error Backend is offline or received critical error"?

A colleague of mine also tried and got the same error with different .txt files and different team names than mine and got the same error.

**Comment by anicolson** [comment]
Can confirm that I also cannot submit to findings-public-test-set. Others seem fine.

**Comment by jbdel** [comment]
I just did a ground truth submission again and everything seems fine.
What is the size of your file? 
can one of you guys send me your file at jbdel at stanford dot edu? Thanks for your patience

**Comment by jbdel** [comment]
I did increase the upload timeout, in case your files are too big

**Comment by jbdel** [comment]
Thanks oscarloch for providing me a file. It allowed me to fix the issue. 
Please tell me if your face further problems.
