### ISSUE TITLE
mimic_cxr_sectioned.csv

### ISSUE THREAD

**Issue by StevenSong** [Stanford-AIMI/RRG24#3]
Thank you guys for putting together this challenge, along with the discharge challenge too!

Just wanted to confirm that `mimic_cxr_sectioned.csv` should be generated from the source note `.txt` files using the code from `MIMIC-CXR-JPG` code repo: https://doi.org/10.5281/zenodo.2591653?

Also a minor suggestion that it's not immediately clear that one should use `MIMIC-CXR-JPG` for the image dataset either, it's obvious enough after looking at the file structure and the `make-interpret-mimic-cxr.py` script but maybe others might benefit from these clarifications

**Comment by jbdel** [comment]
Correct! using this script:
[https://github.com/MIT-LCP/mimic-cxr/blob/master/txt/create_section_files.py](https://github.com/MIT-LCP/mimic-cxr/blob/master/txt/create_section_files.py)
