### ISSUE TITLE
How do I participate in the "Large scale Radiology Report Generation and Sharing Task" task?

### ISSUE THREAD

**Issue by mk-runner** [Stanford-AIMI/RRG24#4]

**Comment by jbdel** [comment]
Hello,

Please visit https://stanford-aimi.github.io/RRG24/ and read the section 2. Data. You can already train a system and validate it on the validation set. The release of the public and hidden test dataset will be April 12th (Friday), 2024, where you will be able to submit your predictions online.

Best,
