### ISSUE TITLE
make-interpret-mimic-cxr.py is down

### ISSUE THREAD

**Issue by swhoosh** [Stanford-AIMI/RRG24#5]
Just as the title said, it seemed that make-interpret-mimic-cxr.py is currently down. https://storage.googleapis.com/misc_jb/make-interpret-mimic-cxr.py

**Comment by jbdel** [comment]
Thanks, new link is up
https://storage.googleapis.com/vilmedic_dataset/RRG24/make-interpret-mimic-cxr.py
