### ISSUE TITLE
Release of test dataset? 

### ISSUE THREAD

**Issue by denisparra** [Stanford-AIMI/RRG24#6]
HI! Our team was waiting for the release of the public and hidden test dataset: announced in the website for April 12th (Friday), 2024. We saw no update on the website https://stanford-aimi.github.io/RRG24/ or in huggingface, can you tell us please if we are missing where to find it?

Another question we have: is there going to be a public leaderboard to know hw well are participatings doing during the month the challenge is happening ? or you are going to simple receive the submissions up to May 10th? In this case, where are you going to be receiving the submissions?

thanks !

Denis & iHealth Chile team

**Comment by jbdel** [comment]
hello,

Data will be released very soon, we are making sure the Stanford provided data have the green light for release.

Stay tuned.

**Comment by denisparra** [comment]
OK thanks about the response about the release date. Now:
1. Are you now providing more time to submit the generated reports since you are releasing the dataset later? AFAIK is still May 10th.
2. Sorry for the insistence, but again I'd like to know whether there will be a public leaderboard during the period the test set is available
3. Could you please provide further information about how/where can we submit our predictions?

thanks!

**Comment by jbdel** [comment]
1) yes, we will push the deadline
2) There will be a public leaderboard that will be released at the same time as the test set. 
3) you will be able to submit your prediction in the same portal as the public leaderboard
