### ISSUE TITLE
Have public and hidden test dataset been released?

### ISSUE THREAD

**Issue by swhoosh** [Stanford-AIMI/RRG24#7]
According to the RRG24 website, they stated that the test dataset would be released on April 12. However, today I couldn't find it anywhere. Does anyone know where it has been released?

![image](https://github.com/Stanford-AIMI/RRG24/assets/70953480/7f247ae3-de52-4369-9d9b-8e94f052a720)

**Comment by oscarloch** [comment]
It has not yet been released. Check out: https://github.com/Stanford-AIMI/RRG24/issues/6
