### ISSUE TITLE
Question about generating empty findings/impression 

### ISSUE THREAD

**Issue by oscarloch** [Stanford-AIMI/RRG24#8]
Hi! Given the newly released [test set](https://huggingface.co/datasets/StanfordAIMI/interpret-cxr-test-public):

Q1: When we are evaluated for the findings section of the [leaderboard](https://vilmedic.app/misc/bionlp24/leaderboard), do we have to generate findings for all the reports in the test, or only those for which findings are present?

Q2: In the case of all reports, should our models predict an empty findings section?

Thank you so much for clarifying!

**Comment by jbdel** [comment]
For test-public and test-hidden, only generate findings or impression for an image when the findings or impression string exists. For public, you have the ground truth, for test, the string is "to_generate".

Example:
`import datasets
dataset = datasets.load_dataset("StanfordAIMI/interpret-cxr-test-hidden/")
findings_to_generate = [s for s in dataset["test"] if s["findings"]]
`
