### ISSUE TITLE
Empty reports in provided train_mimic.json

### ISSUE THREAD

**Issue by oscarloch** [Stanford-AIMI/RRG24#9]
Hi!,

By looking at the train_mimic.json created using the [make-interpret-mimic-cxr.py](https://storage.googleapis.com/vilmedic_dataset/RRG24/make-interpret-mimic-cxr.py) script, I found that there are a lot of empty reports where the findings and impression sections are empty. However, when looking at the unprocessed reports from the original MIMIC dataset, you can see that there is either findings or impression.
![Screenshot_1](https://github.com/Stanford-AIMI/RRG24/assets/69605823/7afad032-98dd-476e-b175-ecfe6927d33b)

Is this on purpose? Can we try to replace the missing data? I'm worried that using the current data could teach the models to produce empty reports

Thank you so much!

**Comment by jbdel** [comment]
Hello, 

Some reports in mimic are indeed empty / non-existent. 
I dont have the exact numbers in mind, but 10K seems a reasonable amount.

JB
